version: '3.9'

services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./.db-data/postgres-data:/var/lib/postgresql/data
